config/routes.rb
Rails.application.routes.draw do
  get "admin" => "admin#index"
  resources :support_requests, only: %i[ index update ]
  resources :users
  resource :session
  resources :passwords, param: :token
  resources :orders
  resources :line_items
  resources :carts
  # get "store/index"
  root "store#index", as: "store_index"
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_cart.html.erb
<% if cart and not cart.line_items.empty? %>
  <div id="cart" class="bg-white rounded p-2">
    <%= render cart %>
  </div>
<% else %>
  <div id="cart">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Depot" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-green-700">
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
    </header>
    <section class="flex">
      <nav class="bg-green-900 p-6">
        <%= render partial: 'layouts/cart', locals: {cart: @cart} %>
        <ul class="text-gray-300 leading-8">
          <li><a href = "/">Home</a></li>
          <li><a href = "/questions">Questions</a></li>
          <li><a href = "/news">News</a></li>
          <li><a href = "/contact">Contact</a></li>
        </ul>

        <hr class="my-2">
        <ul class="text-gray-300 leading-8">
          <% if authenticated? %>
            <li>
              <%= link_to "Orders", orders_path %>
            </li>
            <li>
              <%= link_to "Products", products_path %>
            </li>
            <li>
              <%= link_to "Users", users_path %>
            </li>
            <li>
              <%= button_to "Logout", session_path, method: :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to "Login", new_session_path %>
            </li>
          <% end %>
        </ul>
      </nav>
      <main class="container mx-auto mt-28 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>